on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Build all and release

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
            - name: Build library
              run: .github/workflows/build.sh
              working-directory: ${{ env.GITHUB_WORKSPACE }}
              env:
                  MATRIX_OS: ${{ matrix.os }}
              shell: bash
            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                name: ${{ matrix.os }}
                path: oremo.kit
                if-no-files-found: error
